USE sparta_spring_personal_project;

CREATE TABLE IF NOT EXISTS SCHEDULE
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    pw VARCHAR(100) NOT NULL,
    writeday VARCHAR(100) NOT NULL,
    updateday VARCHAR(100) NOT NULL
)